### ISSUE TITLE
What license is applied to this project?

### ISSUE THREAD

**Issue by sungholee3526** [lolchocotaco/Histogram-Equalization#1]
As the title, what license is applied to this project, and what rules there are to follow if I use the source code?

**Comment by rgruener** [comment]
We never really chose on a license for this since I guess we never figured it would be used by anybody. We did place this on public github so anybody could reference it so I would say feel free to use it. Perhaps if downright copying anything just provide a reference this repository.

**Comment by sungholee3526** [comment]
Thank you for the positive response!
